---
- name: Install dev tools
  homebrew:
    name:
      - git
      - tig
      - htop
      - tree
      - ag
      - tmux

- name: Install cask dev tools 
  homebrew_cask:
    name:
      - slack
      - iterm2

- name: Tap ApoptOpenJDK versions
  homebrew_tap:
    name: AdoptOpenJDK/openjdk
  when: "install_java|bool"

- name: Install Java
  homebrew_cask:
    name: adoptopenjdk8
  when: "install_java|bool"

- name: Install Scala
  homebrew:
    name:
      - scala
      - sbt
  when: "install_scala|bool"

- name: Install Haskell
  homebrew:
    name: ghc
  when: "install_haskell|bool"
