---
- name: Install dev tools
  homebrew:
    name:
      - tig
      - htop
      - tree
      - ag

- name: Install cask dev tools 
  homebrew_cask:
    name:
      - slack
      - iterm2
      - docker
      # Editors
      - visual-studio-code
      - intellij-idea-ce

- name: Tap ApoptOpenJDK versions
  homebrew_tap:
    name: AdoptOpenJDK/openjdk
  when: "install_java|bool"

- name: Install Java
  homebrew_cask:
    name: adoptopenjdk8
  when: "install_java|bool"

- name: Install Scala
  homebrew:
    name:
      - scala
      - sbt
  when: "install_scala|bool"

- name: Install Haskell
  homebrew:
    name: ghc
  when: "install_haskell|bool"
