---
- name: Ensure homebrew is updated 
  homebrew:
    state: latest
    update_homebrew: yes

- name: Tap homebrew caskroom/cask
  homebrew_tap:
    tap: "caskroom/cask"

- import_tasks: apps.yml
  when: "install_apps|bool"
  tags: apps

- import_tasks: dev-tools.yml
  when: "install_dev_tools|bool"
  tags: dev-tools